<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DIN80016857" name="com.ge.corp.DigitalConnect.ec_automationpoc.scripts.EC_Configuration" tests="1" failures="0" timestamp="23 Dec 2019 13:37:42 GMT" time="0.038" errors="1">
  <testcase name="ec_config" time="0.038" classname="com.ge.corp.DigitalConnect.ec_automationpoc.scripts.EC_Configuration">
    <error type="java.io.FileNotFoundException" message="Source &#039;C:\Users\sareddyc\cfBinaries\ecagent_windows_sys&#039; does not exist">
      <![CDATA[java.io.FileNotFoundException: Source 'C:\Users\sareddyc\cfBinaries\ecagent_windows_sys' does not exist
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1074)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at com.ge.corp.DigitalConnect.ec_automationpoc.scripts.BaseTest_EnterpriseConnect.copyFile(BaseTest_EnterpriseConnect.java:55)
	at com.ge.corp.DigitalConnect.ec_automationpoc.scripts.EC_Configuration.ec_config(EC_Configuration.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ec_config -->
</testsuite> <!-- com.ge.corp.DigitalConnect.ec_automationpoc.scripts.EC_Configuration -->
